### PR TITLE
fix: SDDM login screen not working

### PR DESCRIPTION
**Pull request by Maxwelldoug**
This pull request, by copying config from a known good install, gets SDDM working at a bare minimum level. The UI is now usable and login succeeds. Plasma only partially loads (pressing the power button gets the correct logout menu and the mouse cursor loads, but the rest of the system such as desktop and taskbar do not)

### CODE REVIEW

**Comment by Maxwelldoug** [comment]
This fixes https://github.com/Vanilla-Kattleya/plasma-image/issues/19

**Comment by Maxwelldoug** [comment]
Made a slight change to pull in the latest version of this data from the debian repositories rather than manually including specific files from my own config.

**Comment by Maxwelldoug** [comment]
The most recent changes seem to have broken it again. For some reason, the desktop-base package is basically empty despite it being as expected in debian's own repositories.

**Comment by Maxwelldoug** [comment]
This is very much a workaround but didn't want to leave the PR in a regressed state so we leave it as is for now.

**Comment by Maxwelldoug** [comment]
Side note, [533344f](https://github.com/Vanilla-Kattleya/plasma-image/pull/20/commits/533344f2114f7509485f2b6133a2d04cdd870ed9) is the only commit to this PR that actually does anything, if I could figure out how to remove all the others from the history, I would.

**Comment by kbdharun** [comment]
> Side note, [533344f](https://github.com/Vanilla-Kattleya/plasma-image/pull/20/commits/533344f2114f7509485f2b6133a2d04cdd870ed9) is the only commit to this PR that actually does anything, if I could figure out how to remove all the others from the history, I would. I will work in a separate branch from here to avoid clogging up this PR.

Will fix it up for you.

**Pull request merged**
